description: a Helm chart to install virtual kubelet with Azure provider in an AKS or AKS-engine cluster.
maintainers:
- email: guwe@microsoft.com
  name: Guoxun Wei
- email: peni@microsoft.com
  name: Pengfei Ni
name: virtual-kubelet-aci-for-aks
sources:
- https://github.com/virtual-kubelet/azure-aci
version: 1.4.0
